# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IBGEWorkloadManagement
                                 A QGIS plugin
 Gerenciador de cargas de trabalho para a produção cartográfica do Instituto Brasileiro de Geografia e Estatística (IBGE)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-22
        copyright            : (C) 2025 by Victor Marotta/IBGE
        email                : victor.marotta@ibge.gov.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IBGEWorkloadManagement class from file IBGEWorkloadManagement.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .workfload_management import IBGEWorkloadManagement
    return IBGEWorkloadManagement(iface)
